name: 'Nestjs Boilerplate API Modular - Lint'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-linters:
    name: Run Linters
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [18x, 20x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
